spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mse_database
    username: mse_database
    password: mse_database
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #driver-class-name: com.mysql.cj.jdbc.Driver